### ISSUE TITLE
File location error in README.md

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/eShopLite-SemanticSearch-AzureAISearch#1]
**Description**
The file location of [Aspire AppHost](https://github.com/Azure-Samples/eShopLite-SemanticSearch-AzureAISearch/blob/main/README.md#aspire-apphost) `.\src\eShopAppHost\eShopAppHost.csproj` is wrong in README.md, as follow:
![image](https://github.com/user-attachments/assets/51f9b3d7-0a41-4389-9273-8d7c6a70552d)

**Suggestion**
Update to `.\src\eShopAppHost`.

@elbruno, @PabloNunes and @hemarina for notification.

**Comment by elbruno** [comment]
Thanks for the suggestion!

Fixed in https://github.com/Azure-Samples/eShopLite-SemanticSearch-AzureAISearch/commit/0316986c6855522a598159c4c25f0c3012c40e2f

Best
