### ISSUE TITLE
Readme.md description is not clear

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/eShopLite-SemanticSearch-AzureAISearch#3]
**Description**
The readme does not clearly describe where to add the code in the figure below.
![image](https://github.com/user-attachments/assets/0cc27800-6ac0-4cb4-b6a1-607aee47010f)
 
**Suggestion**
Change the above code to the following command:
```
cd src/Products
dotnet user-secrets set "ConnectionStrings:openaidev" "Endpoint=https://<endpoint>.openai.azure.com/;Key=<Azure OpenAI Service key>;"
dotnet user-secrets set "ConnectionStrings:azureaisearchdev" "Endpoint=https://<endpoint>.search.windows.net/;Key=<Azure AI Search key>;"
 ```

@elbruno, @PabloNunes and @hemarina for notification.

**Comment by elbruno** [comment]
Thanks for the suggestion.

Readme updated on https://github.com/Azure-Samples/eShopLite-SemanticSearch-AzureAISearch/commit/12c5d2f217175d81f35fa8585494846239956291

Best!
